services:
  mysql:
    image: mariadb:latest
    container_name: mysql_pcs
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - db:/var/lib/mysql

  php:
    build: ./php
    ports:
      - "82:80"
    volumes:
      - ./:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin
    ports:
      - "8085:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: '3306'
      PMA_USER: homestead
      PMA_PASSWORD: secret
      PMA_ARBITRARY: 1
    depends_on:
      - mysql

volumes:
  db:
